= Asciidoctor Rouge
:source-language: ruby
// custom
:gem-name: asciidoctor-rouge
:gem-version: 0.0.0.dev
:gh-name: jirutka/{gem-name}
:gh-branch: master
:codacy-id: d2ed58f5f3f949a19bab7637fe7d0bdb

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}[Build Status, link="https://travis-ci.org/{gh-name}"]
image:https://api.codacy.com/project/badge/Coverage/{codacy-id}["Test Coverage", link="https://www.codacy.com/app/{gh-name}"]
image:https://api.codacy.com/project/badge/Grade/{codacy-id}["Codacy Code quality", link="https://www.codacy.com/app/{gh-name}"]
image:https://img.shields.io/gem/v/{gem-name}.svg?style=flat[Gem Version, link="https://rubygems.org/gems/{gem-name}"]
image:https://img.shields.io/badge/yard-docs-blue.svg[Yard Docs, link="http://www.rubydoc.info/github/{gh-name}/{gh-branch}"]
endif::env-github[]


This project provides an http://asciidoctor.org/[Asciidoctor] extension for highlighting source listing blocks using http://rouge.jneen.net/[Rouge] – a pure-ruby code highlighter that is compatible with pygments.

It supports all Asciidoctor features such as http://asciidoctor.org/docs/user-manual/#callouts[callouts], highlighting of specified lines (attribute `highlight`), http://asciidoctor.org/docs/user-manual/#passthroughs[passthroughs] inside a code and all other substitutions.

This extension is highly customizable and modular.


== Installation

To install (or update to the latest version):

[source, sh, subs="+attributes"]
gem install {gem-name}

or to install the latest development version:

[source, sh, subs="+attributes"]
gem install {gem-name} --pre


== Usage

Set attribute `source-highlighter` to `rouge`; globally or in the document.

[source, sh, subs="+attributes"]
asciidoctor -r {gem-name} -a source-highlighter=rouge Example.adoc


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
