inherit_from: ../.rubocop.yml

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  IgnoredMethods: [ expect, let ]

# I use it for purpose with Corefines, e.g. `using Corefines::String::unindent`.
Style/ColonMethodCall:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
